# Generated by Django 5.1.4 on 2024-12-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('altura', models.FloatField(help_text='Altura em cm')),
                ('peso', models.FloatField(help_text='Peso em kg')),
                ('imc', models.FloatField(blank=True, help_text='Índice de Massa Corporal', null=True)),
            ],
        ),
    ]
